package com.example.yjy.smarthouse_android.bussiness.protocol;

/**
 * Created by yjy on 17-4-29.
 */
public class BaseProtocal {

    /**
     * uniform request format:
     *
     * {"action":1,"object":3333}
     * or
     * {"action":1,"object":3333,"attach":"xxx"}
     *
     *
     * uniform response format:
     * {"action":1,"body":YOUR_JSON_OBJECT}
     *
     *
     * example:
     * request:{"action":1400,"object":}
     * response:{"action":1400,"body":{"device_list":[{"ID":"2000","name":"device1","location":"bedroom","type":"light"},{"ID":"2001","name":"device2","location":"kitchen","type":"light"}]}}
     *
     * The data structure of YOUR_JSON_OBJECT will be discussed and defined
     * once we incur with different bussiness cases
     *
     **/

    /** actions **/
    //normal button
    public static final int OPERATION_CLOSE = 1000;
    public static final int OPERATION_OPEN = 1001;
    //camera
    public static final int SHOOT = 1100;
    public static final int PICK = 1101;
    //data collector
    public static final int START = 1200;
    public static final int STOP = 1201;
    public static final int UPLOAD = 1202;
    //air conditioner
    public static final int SET = 1300;
    //central controller
    public static final int LIST_DEVICE = 1400;

    /** object ids are generated by central controller **/



    /** controller **/
    public static final int ID_CONTROLLER = 5794867;

}
